### ISSUE TITLE
rqt_moveit: Begin topic monitoring automatically 

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_moveit#1]
_From @130s on April 3, 2013 17:53_

Right now user has to manually choose topics to start monitoring, and start it by right-clicking and choosing `Toggle monitoring`. It would be nice if this is automated.

This might involve changing `rqt_topic`, which is internally used in `rqt_moveit`.

_Copied from original issue: ros-visualization/rqt_robot_plugins#17_

**Comment by dirk-thomas** [comment]
_From @ablasdel on June 9, 2014 18:49_

Setting this to untargeted since it clearly didn't make the hydro release

**Comment by arne48** [comment]
This enhancement might be obsolete now. In the meantime the topics plugin introduced checkboxes which make starting the monitoring of a topic very easy.
A second aspect is the high bandwidth of the topics containing pointclouds. Assuming all of them are used and would listen automatically from the beginning this might have a high impact on the performance of the plugin.
I would consider the current condition as the most viable for this plugin. As the state of listening to a topic is easy to toggle but at the same time the default state is considering the plugin's performance.

**Comment by arne48** [comment]
I think after half a year now and no opposing opinion this issue can be closed.
